# Generated by Django 5.2.9 on 2026-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_video_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
