# Generated by Django 5.2.9 on 2026-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Rolex', 'Rolex'), ('Rado', 'Rado'), ('Patek Philippe', 'Patek Philippe'), ('Audemars Piguet', 'Audemars Piguet'), ('Omega', 'Omega')], default='Rolex', max_length=50),
        ),
    ]
