# Generated by Django 5.2.9 on 2026-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Rolex', 'Rolex'), ('Rado', 'Rado'), ('Patek Philippe', 'Patek Philippe'), ('Audemars Piguet', 'Audemars Piguet'), ('Omega', 'Omega'), ('Cartier', 'Cartier')], default='Rolex', max_length=50),
        ),
    ]
